const CartActionTypes = {
  TOGGLE_CART_HEDDIN: "TOGGLE_CART_HEDDIN",
  ADD_ITEMS: "ADD_ITMES",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};

export default CartActionTypes;
